Try treating lint failure as a success to test

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -25,13 +25,17 @@ jobs:
             - name: Install dependencies
               run: pnpm install
 
-            - name: Run ESLint
+            - name: Run ESLint (Expecting failure)
               run: |
                   cd tests/react-ts
                   pnpm lint
-                  if [ $? -eq 0 ]; then
-                    echo "ESLint passed, which is unexpected. Marking this as a failure."
-                    exit 1
+                  lint_exit_code=$?
+                  echo "The exit code of pnpm lint is: $lint_exit_code"
+
+                  if [ $lint_exit_code -eq 0 ]; then
+                      echo "ESLint passed, which is unexpected. Marking this as a failure."
+                      exit 1
                   else
-                    echo "ESLint failed, which is expected. Marking this as a success."
+                      echo "ESLint failed, which is expected. Marking this as a success."
+                      exit 0
                   fi
